# Generated by Django 4.2.11 on 2024-03-11 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0003_alter_mailform_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailform',
            name='Password',
        ),
    ]
